### ISSUE TITLE
[Android Bootcamp] Project 0: Prework - TodoApp - Ready for Review

### ISSUE THREAD

**Issue by nastjashevchenko** [nastjashevchenko/SimpleToDo#1]
Required user stories are ready in my pre-work app, please review /cc @codepathreview @codepath

**Comment by nastjashevchenko** [comment]
New features added:
- SQLite integration, using ActiveAndroid ORM;
- Custom adapter for Task object;
- Support for selecting the priority.

**Comment by nastjashevchenko** [comment]
It is not on your list, but I also made Task (class for todo tasks) Parcelable, which is in my opinion better approach than transfer it's fields between Activities

**Comment by nidhi1608** [comment]
Hi Anastasiya,

Thanks for applying and submitting your pre-work. Based on your LinkedIn it is unclear if you meet the [selection criteria for the course](http://courses.codepath.com/snippets/intro_to_android/selection_criteria). In particular:
- Experience developing software with object-oriented programming languages
- Existing knowledge of Java or ability to ramp up on the language quickly
- 2+ years of professional software development experience (average participant has 5+ years) building software.

Can you review that and let me know if you can confirm that you meet the requirements? If not, I can add you as a "remote self-paced observer" so you can participate in the program and learn at your pace. In the meantime, you should also check out the [resources we provide here](http://courses.codepath.com/snippets/intro_to_android/email_faq#heading-i-dont-have-much-or-any-professional-software-development-experience-how-can-codepath-help-me).

**Comment by nastjashevchenko** [comment]
Hi, Nidhi!
Thank you for your reply.
For these points I can answer:
- I have no experience in "pure" software development, but I have 4+ years as QA and SET (about 2,5 years with test automation);
- I use Java for test purposes for about 2 years in total, may be my knowledge is not on expert level, but I am sure, I can jump fast into deeper Java;
- For the first one: as I said, I have no experience in building apps for users, but test frameworks using Java and python (which are OO languages).

In addition now I also started taking courses via Udacity. 
I have seen this requirements (about 2+ years in SE positions) before applied and sent email, If I have any chance to be involved with my adjacent experience and received reply from Nathan that in this case I have chance depending on my pre-work.

I hope it became more clear now and feel free ask more questions if you have.

I am waiting for your reply,
Thanks.

**Comment by nastjashevchenko** [comment]
@nidhi1608, please see my comment above

**Comment by nidhi1608** [comment]
Thanks for the clarification Anastasiya. Your pre-work looks good, this exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project.

The next step is to continue working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) and to <b>schedule a short 5-10 minute phone conversation</b> [here](https://www.google.com/calendar/selfsched?sstoken=UU5IOEduOWEtRDg5fGRlZmF1bHR8NWRiNTI5ZWJmMjVjODg1OGVhMmU0NDg5Nzc2NDRlNTc). Navigate to [today's date and onward from there](https://www.google.com/calendar/selfsched?sstoken=UU5IOEduOWEtRDg5fGRlZmF1bHR8NWRiNTI5ZWJmMjVjODg1OGVhMmU0NDg5Nzc2NDRlNTc) and choose a 15-minute slot. Let us know if none of those times work.

Once you select a slot, can you make sure to include best number to reach you at to the invite? Look forward to chatting soon!

**Comment by nastjashevchenko** [comment]
Added sorting by priority and dialog to confirm deletion.
I didn't have enough time today to work on "DialogFragment instead of EditActivity", but wanted to touch dialogs in Android, so I added this confirmation question when trying to delete. Also I think this is useful user story. It is not on gif yet.

**Comment by nidhi1608** [comment]
Nice, good to see you implemented many extensions. Can you also update the gif file with these changes? Look forward to chatting with you soon.

**Comment by nastjashevchenko** [comment]
@nidhi1608, thank you for feedback!
I've added new gif with new features. Looking forward to talk to you.
